import { Poliza } from "@/types/poliza.interface";

export const mockPolizas: Poliza[] = [
  {
    id_poliza: 1,
    contratante: "Empresa ABC S.A.",
    asegurado: "Juan Pérez García",
    cia: "Rimac Seguros",
    ram: "Vehicular",
    prod: "Todo Riesgo",
    poliza: "POL-2025-001",
    mo: "PEN",
    vig_inicio: "2025-01-01",
    vig_fin: "2025-12-31",
    sub_agente: "Agente 001",
    descripcion_poliza: "Cobertura completa para vehículo Toyota Corolla 2020",
    esta_activa: true,
    fecha_creacion: "2024-12-01T10:00:00Z",
    fecha_actualizacion: "2024-12-01T10:00:00Z",
    tipo_vigencia: "ANUAL",
    fecha_emision: "2024-12-01",
    comision_compania: 15,
    comision_sub_agente: 70,
    descripcion_asegurado: "Vehículo Toyota Corolla 2020, placa ABC-123",
    ejecutivo_cuenta: "María González",
    mas_informacion: "Cliente preferencial con descuento adicional",
  },
  {
    id_poliza: 2,
    contratante: "Constructora XYZ Ltda.",
    asegurado: "Constructora XYZ Ltda.",
    cia: "Pacífico Seguros",
    ram: "SCTR",
    prod: "Pensión",
    poliza: "POL-2025-002",
    mo: "PEN",
    vig_inicio: "2025-02-01",
    vig_fin: "2025-01-31",
    sub_agente: "Agente 002",
    descripcion_poliza:
      "Seguro Complementario de Trabajo de Riesgo para 50 trabajadores",
    esta_activa: true,
    fecha_creacion: "2024-12-15T14:30:00Z",
    fecha_actualizacion: "2024-12-15T14:30:00Z",
    tipo_vigencia: "ANUAL",
    fecha_emision: "2024-12-15",
    comision_compania: 12,
    comision_sub_agente: 70,
    descripcion_asegurado: "Empresa constructora con 50 trabajadores en obra",
    ejecutivo_cuenta: "Carlos Rodríguez",
    mas_informacion: "Incluye cobertura adicional para maquinaria pesada",
  },
  {
    id_poliza: 3,
    contratante: "María González",
    asegurado: "María González",
    cia: "Mapfre",
    ram: "Salud",
    prod: "Plan Familiar",
    poliza: "POL-2025-003",
    mo: "PEN",
    vig_inicio: "2025-03-01",
    vig_fin: "2025-02-28",
    sub_agente: "Agente 003",
    descripcion_poliza:
      "Plan de salud familiar con cobertura ambulatoria y hospitalaria",
    esta_activa: true,
    fecha_creacion: "2024-12-20T09:15:00Z",
    fecha_actualizacion: "2024-12-20T09:15:00Z",
    tipo_vigencia: "ANUAL",
    fecha_emision: "2024-12-20",
    comision_compania: 18,
    comision_sub_agente: 70,
    descripcion_asegurado: "Familia de 4 miembros: padre, madre y 2 hijos",
    ejecutivo_cuenta: "Ana López",
    mas_informacion: "Cobertura dental incluida en el plan premium",
  },
  {
    id_poliza: 4,
    contratante: "Tienda El Sol S.A.",
    asegurado: "Tienda El Sol S.A.",
    cia: "La Positiva",
    ram: "Multiriesgo",
    prod: "Comercio",
    poliza: "POL-2025-004",
    mo: "PEN",
    vig_inicio: "2025-01-15",
    vig_fin: "2025-01-14",
    sub_agente: "Agente 004",
    descripcion_poliza:
      "Seguro multiriesgo para local comercial con cobertura contra incendio y robo",
    esta_activa: false,
    fecha_creacion: "2024-11-10T16:45:00Z",
    fecha_actualizacion: "2024-12-01T11:20:00Z",
    tipo_vigencia: "ANUAL",
    fecha_emision: "2024-11-10",
    comision_compania: 10,
    comision_sub_agente: 70,
    descripcion_asegurado: "Local comercial de 150m² en zona comercial",
    ejecutivo_cuenta: "Pedro Sánchez",
    mas_informacion: "Cliente con póliza anterior que fue renovada",
  },
  {
    id_poliza: 5,
    contratante: "Carlos Rodríguez",
    asegurado: "Carlos Rodríguez",
    cia: "Rimac Seguros",
    ram: "Vehicular",
    prod: "Responsabilidad Civil",
    poliza: "POL-2025-005",
    mo: "USD",
    vig_inicio: "2025-04-01",
    vig_fin: "2025-03-31",
    sub_agente: "Agente 001",
    descripcion_poliza:
      "Seguro de responsabilidad civil para motocicleta Honda CB300R",
    esta_activa: true,
    fecha_creacion: "2024-12-22T13:10:00Z",
    fecha_actualizacion: "2024-12-22T13:10:00Z",
    tipo_vigencia: "ANUAL",
    fecha_emision: "2024-12-22",
    comision_compania: 8,
    comision_sub_agente: 70,
    descripcion_asegurado: "Motocicleta Honda CB300R 2019",
    ejecutivo_cuenta: "Luis Torres",
    mas_informacion: "Cliente nuevo, primera póliza con la compañía",
  },
];
