import { Cliente } from '@/types/cliente.interface';

export const mockClientes: Cliente[] = [
    {
        id_cliente: '1a2b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6',
        nombre: 'Juan',
        apellido: 'Pérez García',
        email: 'juan.perez@example.com',
        telefono: '+51 987 654 321',
        telefono_secundario: '+51 912 345 678',
        documento_identidad: '12345678',
        tipo_documento: 'DNI',
        fecha_nacimiento: '1985-05-15',
        direccion: 'Av. Los Rosales 123, Urb. Las Flores',
        distrito: 'San Isidro',
        provincia: 'Lima',
        departamento: 'Lima',
        ocupacion: 'Ingeniero de Sistemas',
        empresa: 'Tech Solutions SAC',
        estado_civil: 'CASADO',
        contacto_emergencia_nombre: 'María Pérez',
        contacto_emergencia_telefono: '+51 987 111 222',
        contacto_emergencia_relacion: 'Esposa',
        esta_activo: true,
        fecha_registro: '2024-01-15T10:30:00',
        broker_asignado: 'broker-uuid-1',
        broker_nombre: 'Carlos Rodríguez',
    },
    {
        id_cliente: '2b3c4d5e-6f7g-8h9i-0j1k-l2m3n4o5p6q7',
        nombre: 'María',
        apellido: 'González López',
        email: 'maria.gonzalez@example.com',
        telefono: '+51 998 765 432',
        documento_identidad: '87654321',
        tipo_documento: 'DNI',
        fecha_nacimiento: '1990-08-22',
        direccion: 'Calle Las Magnolias 456, San Borja',
        distrito: 'San Borja',
        provincia: 'Lima',
        departamento: 'Lima',
        ocupacion: 'Contadora',
        empresa: 'Contabilidad Total',
        estado_civil: 'SOLTERO',
        contacto_emergencia_nombre: 'Pedro González',
        contacto_emergencia_telefono: '+51 987 222 333',
        contacto_emergencia_relacion: 'Padre',
        esta_activo: true,
        fecha_registro: '2024-02-20T14:45:00',
        broker_asignado: 'broker-uuid-2',
        broker_nombre: 'Ana Martínez',
    },
    {
        id_cliente: '3c4d5e6f-7g8h-9i0j-1k2l-m3n4o5p6q7r8',
        nombre: 'Roberto',
        apellido: 'Sánchez Díaz',
        email: 'roberto.sanchez@example.com',
        telefono: '+51 965 432 198',
        documento_identidad: '45678912',
        tipo_documento: 'DNI',
        fecha_nacimiento: '1978-12-10',
        direccion: 'Jr. Los Tulipanes 789, Miraflores',
        distrito: 'Miraflores',
        provincia: 'Lima',
        departamento: 'Lima',
        ocupacion: 'Médico Cirujano',
        empresa: 'Clínica San Pablo',
        estado_civil: 'DIVORCIADO',
        contacto_emergencia_nombre: 'Carmen Díaz',
        contacto_emergencia_telefono: '+51 987 333 444',
        contacto_emergencia_relacion: 'Hermana',
        esta_activo: true,
        fecha_registro: '2024-03-10T09:15:00',
        broker_asignado: 'broker-uuid-1',
        broker_nombre: 'Carlos Rodríguez',
    },
    {
        id_cliente: '4d5e6f7g-8h9i-0j1k-2l3m-n4o5p6q7r8s9',
        nombre: 'Ana',
        apellido: 'Torres Ramírez',
        email: 'ana.torres@example.com',
        telefono: '+51 976 543 210',
        documento_identidad: 'CE123456',
        tipo_documento: 'CE',
        fecha_nacimiento: '1995-03-28',
        direccion: 'Av. Primavera 321, Surco',
        distrito: 'Surco',
        provincia: 'Lima',
        departamento: 'Lima',
        ocupacion: 'Diseñadora Gráfica',
        empresa: 'Creative Studio',
        estado_civil: 'CONVIVIENTE',
        contacto_emergencia_nombre: 'Luis Torres',
        contacto_emergencia_telefono: '+51 987 444 555',
        contacto_emergencia_relacion: 'Pareja',
        esta_activo: true,
        fecha_registro: '2024-04-05T16:20:00',
        broker_nombre: 'Ana Martínez',
    },
    {
        id_cliente: '5e6f7g8h-9i0j-1k2l-3m4n-o5p6q7r8s9t0',
        nombre: 'Carlos',
        apellido: 'Mendoza Vargas',
        email: 'carlos.mendoza@example.com',
        telefono: '+51 954 321 876',
        documento_identidad: '78912345',
        tipo_documento: 'DNI',
        fecha_nacimiento: '1982-11-05',
        direccion: 'Calle Los Cedros 654, La Molina',
        distrito: 'La Molina',
        provincia: 'Lima',
        departamento: 'Lima',
        ocupacion: 'Abogado',
        empresa: 'Estudio Jurídico Mendoza & Asociados',
        estado_civil: 'CASADO',
        contacto_emergencia_nombre: 'Patricia Vargas',
        contacto_emergencia_telefono: '+51 987 555 666',
        contacto_emergencia_relacion: 'Esposa',
        esta_activo: false,
        fecha_registro: '2023-12-01T11:30:00',
        broker_asignado: 'broker-uuid-3',
        broker_nombre: 'Jorge Fernández',
    },
];
